/*
	1. What is a Graph?
	2. Terminologies of a graph
		- Directed and undirected graph
		- Edge list
		- Convert from undirected into directed
		- Unweighted edge and weighted edge
		- Unweighted graph and weighted graph
		- Cyclic graph and acyclic graph
		- Degree
		- Indegree and outdegree
		- Path: valid and invalid path
		- Components (disconnected and connected graph)
	3. Interview Based Question
		- Practical use of graph
		- Is each graph a tree?
		- Is each tree a graph?
		- Clone a graph
	4. Graph Creation
		- Using Adjacency Matrix
		- Using Adjacency List
		- Generalize the code of the graph creation
		- HW: Time and space complexity of graph creation?
	5. Traverse the graph
		- BFS Algorithm
		- HW: Time and space complexity of BFS?
		- DFS Algorithm
		- HW: Time and space complexity of DFS?
		- HW: Find the number of components of a graph.
*/

/*
1. What is a Graph?
It is a data structure and combination of edges and nodes.
Invalid path: When any node occurs more than one time in the path.
Read More: Download the PDF Notes Of Graph
*/