/*
📝 What is sliding window technique?
The sliding window is a problem-solving technique that's designed to transform two nested loops into a single loop. It applies to arrays or lists. These problems are painless to solve using a brute force approach in O(n²) or O(n³). However, the sliding window technique can reduce the time complexity to O(n).

📝 Sliding window variants:
    1. Fixed size window
	2. Variable size window
	3. Two pointer approach
	4. Optimization approach

📝 Master sliding window through this resource:
Resource 1: https://leetcode.com/discuss/general-discussion/1122776/summary-of-sliding-window-patterns-for-subarray-substring
Resource 2: https://leetcode.com/discuss/interview-question/3722472/mastering-sliding-window-technique-a-comprehensive-guide
*/