// Hashmaps and Tries Theory

/*
1. What is Maps?
Maps are the associative containers that store sorted key-value pair, in which each key is unique and 
it can be inserted or deleted but keys cannot be changed once they are inserted into the map.
Values associated with keys can be changed.

2. C++ STL Maps Type
I. Ordered Map
II. Unordered Map

I. Ordered Map:
Time Complexity: O(Log N)
Ordered Map is implemented by a Balanced Binary Search Tree.

II. Unordered Map: 
Time Complexity: O(1)
Unordered Map is implemented by Array/Hash table/Bucket array

Note: Maps is ordered map by default
*/